### ISSUE TITLE
Collab: CodeLab x FullstackLA

### ISSUE THREAD

**Issue by leighphan** [codelaboc/hellocodelab#22]
Placeholding for a future collaboration event/workshop with [FullstackLA](https://github.com/fullstackLA) + [MaptimeLA](https://github.com/maptimeLA)!

Partnering w/ our LA pals, @machikoyasuda, @kpearson

**Comment by kangashley** [comment]
October date/location for "boba.js slash hacktober slash la-&-oc code hack fun day" in talks [here](https://github.com/fullstackla/pairing-meetup/issues/66#issuecomment-248403370)! [someone create a boba emoji and insert here]

**Comment by leighphan** [comment]
This collaboration would be for... **Hacktoberfest!** 
https://github.com/blog/2067-hacktoberfest-contribute-to-open-source-in-october

**Comment by leighphan** [comment]
Best weekends would be Oct 8, 15, 29th. Does anyone have a preference on any of those?

We'd be hosting this event in collab w/ our pals at [FullstackLA ](https://github.com/fullstackla/pairing-meetup). Chime in if you have a date preference!

This would be hosted at Pro Desk Space.

**Comment by kpearson** [comment]
Hi there,

Any of those dates work for me. I’m happy to help as needed. Just send me specific tasks.

I’m happy to create an event page on the FullstackLA site and MeetUp.com.

To do this, ideally, I’d like to have:

  \* Event description

  \* Location

  \* Parking info

  \* Logo or presenter image (if thats a thing)

That said, I’ll pots with whatever you have. No pressure. :-)

— Kit

On Wed, Sep 21, 2016 at 2:48 PM Leigh

<
mailto:Leigh notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Best weekends would be Oct 8, 15, 29th. Does anyone have a preference on any of those?

We'd be hosting this event in collab w/ our pals at
https://github.com/fullstackla/pairing-meetup
. Chime in if you have a date preference!

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/codelaboc/hellocodelab/issues/22#issuecomment-248753155
, or

**Comment by machikoyasuda** [comment]
HI!!!! There is organizing going on in 2 issues in 2 different repos. Let's keep it to just one cos I'm getting lost! Click: https://github.com/fullstackla/pairing-meetup/issues/66#issuecomment-248403370
